import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ConditionalNavBar from "./components/ConditionalNavBar";
import { LanguageProvider } from "./components/contexts/LanguageContext";
import { ThemeProvider } from "./components/contexts/themeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LanguageProvider>
          <ThemeProvider>
            <ConditionalNavBar />
            {children}
          </ThemeProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
